DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output/Deliver_student_mad50'          # output folder name used for saving the model, logs and inference results

MODEL:
  NAME          : Segformer                                            # name of the model you are using
  BACKBONE      : mit_b0                                        # model variant
  PRETRAINED    : 'segformers/mit_b0.pth'     # backbone model's weight
  RESUME        : ''                                                # checkpoint file

DATASET:
  NAME          : DELIVER                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : 'DELIVER'                                   # dataset root path
  IGNORE_LABEL  : 255
  MODALS        :  ['img', 'depth', 'event', 'lidar'] # ', , 'event'
TRAIN:
  IMAGE_SIZE    : [256, 256]    # training image size in (h, w)
  BATCH_SIZE    : 8               # batch size used to train
  EPOCHS        : 200             # number of epochs to train
  EVAL_START    : 0             # evaluation interval start
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : True            # use DDP training

LOSS:
  NAME          : OhemCrossEntropy          # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.00006 # 0.00006         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio


EVAL:
  MODEL_PATH    : 'MODEL PATH'
  IMAGE_SIZE    : [256, 256]                            # evaluation image size in (h, w)
  BATCH_SIZE    : 4                                       # batch size used to train
  MSF:
    ENABLE      : false                                   # multi-scale and flip evaluation
    FLIP        : true                                    # use flip in evaluation
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation


TEST:
  MODEL_PATH    : 'output/DELIVER/cmnext_b2_deliver_rgbdel.pth'    # trained model file path
  FILE          : 'DELIVER'                          # filename or foldername
  IMAGE_SIZE    : [1024, 1024]                            # inference image size in (h, w)
  OVERLAY       : false                                   # save the overlay result (image_alpha+label_alpha)